# Generated by Django 2.2.5 on 2023-10-06 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='id_perimssao',
            new_name='id_permissao',
        ),
    ]
