# Generated by Django 3.1.4 on 2023-10-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0003_endereco_alter_emitentedestinatario_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id_funcionario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_perfil',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='id_situacao',
        ),
        migrations.RemoveField(
            model_name='protocolo',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='permissao',
            field=models.CharField(choices=[('GR', 'Gerente'), ('FUN', 'Funcionário'), ('EST', 'Estagiário'), ('VIS', 'Visitante')], default='FUN', max_length=45, verbose_name='Permissão'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=45, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='id_funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='protocolo.funcionario'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='situacao',
            field=models.CharField(choices=[('PEN', 'PENDENTE'), ('RET', 'RETIRADO'), ('CAN', 'CANCELADO')], default='PEN', max_length=45, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='emitentedestinatario',
            name='documento',
            field=models.CharField(max_length=11, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='emitentedestinatario',
            name='email',
            field=models.CharField(max_length=45, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='emitentedestinatario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emitentedestinatario',
            name='nome',
            field=models.CharField(max_length=45, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='emitentedestinatario',
            name='telefone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=45, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.IntegerField(verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=45, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=45, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=45, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='documento',
            field=models.CharField(max_length=11, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(max_length=45, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=45, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='data_entrega',
            field=models.DateField(auto_now_add=True, verbose_name='Data de entrega'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='data_retirada',
            field=models.DateField(verbose_name='Data de retirada'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='qtd_volumes',
            field=models.IntegerField(verbose_name='Volumes'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
        migrations.DeleteModel(
            name='Permissao',
        ),
        migrations.DeleteModel(
            name='Situacao',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
