# Generated by Django 3.1.4 on 2023-10-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0005_auto_20231023_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='situacao',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Retirado', 'Retirado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=45, verbose_name='Situação'),
        ),
    ]
