# Generated by Django 3.1.4 on 2023-10-24 13:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0006_auto_20231023_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emitentedestinatario',
            name='id_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.endereco'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='data_entrega',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de entrega'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='data_retirada',
            field=models.DateField(blank=True, null=True, verbose_name='Data de retirada'),
        ),
    ]
