# Generated by Django 4.2.6 on 2023-11-07 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0009_alter_emitentedestinatario_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='permissao',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Funcionário', 'Funcionário'), ('Estagiário', 'Estagiário'), ('Visitante', 'Visitante')], default='Funcionário', max_length=45, verbose_name='Permissão'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='id_destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_destinatario', to='protocolo.emitentedestinatario'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='id_emitente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_emitente', to='protocolo.emitentedestinatario'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='id_funcionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.funcionario'),
        ),
    ]
