# Generated by Django 4.2.6 on 2023-11-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0011_alter_protocolo_id_destinatario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='nome_funcionario',
            field=models.CharField(default='Funcionário', max_length=45, verbose_name='Funcionario'),
        ),
    ]
