# Generated by Django 4.2.6 on 2023-11-29 00:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0013_funcionario_groups_funcionario_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(choices=[('Pendente', 'Pendente'), ('Retirado', 'Retirado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=45)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.protocolo')),
            ],
        ),
    ]
