# Generated by Django 4.2.6 on 2023-12-01 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0012_protocolo_nome_funcionario'),
        ('protocolo', '0014_historico'),
    ]

    operations = [
    ]
